#%RAML 1.0
title: TipoIdentificacao
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/48f3ff82-1df3-4a4c-a34d-bde550e45f53/
description: Retorno os tipos de registros contidos na coluna tpi_ds_tipo_identificacao da integração A.
mediaType:
  - application/json
version: 1.0.0
protocols:
  - HTTP
  - HTTPS
/tipoIdentificacao:
  get:
    displayName: tipoIdentificacao
    description: Retorna lista com os registros dos tipos de identificação.
    body: {}
    responses:
      "200":
        body:
          application/json:
            example: !include exemplos\tipo-identificacao\get\tipo-identificacao-response.json
    securedBy: []
securedBy: []
